# Generated by Django 5.0.6 on 2024-06-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_id", models.FloatField()),
                ("order_id", models.CharField(max_length=255)),
                ("order_date", models.DateField()),
                ("ship_date", models.DateField(max_length=255)),
                ("ship_mode", models.CharField(max_length=255)),
                ("customer_id", models.CharField(max_length=255)),
                ("customer_name", models.CharField(max_length=255)),
                ("segment", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("postal_code", models.FloatField()),
                ("region", models.CharField(max_length=255)),
                ("product_id", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("sub_category", models.CharField(max_length=255)),
                ("product_name", models.FloatField()),
                ("sales", models.FloatField()),
                ("delivery_time", models.DurationField(blank=True, null=True)),
            ],
        ),
    ]
