# Generated by Django 5.0.6 on 2024-06-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brain", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.CharField(max_length=255)),
                ("customer_name", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("postal_code", models.CharField(max_length=20)),
                ("region", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="sale",
            name="postal_code",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="sale",
            name="product_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="sale",
            name="row_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="sale",
            name="ship_date",
            field=models.DateField(),
        ),
    ]
